#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static SeedSpec6 pnSeed6_main[] = {
    0x01,0x04,0xa1,0x23,0x5d,0xb3,0x00,0x00,
};

static SeedSpec6 pnSeed6_test[] = {
    0x01,0x04,0xa1,0x23,0x5d,0xb3,0x00,0x00,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
